# Generated by Django 5.2 on 2025-04-27 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortlink', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortlink',
            name='short_code',
            field=models.CharField(blank=True, db_index=True, max_length=10, unique=True),
        ),
    ]
