# Generated by Django 5.2 on 2025-04-28 03:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_postimage_thumbnail_alter_postimage_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('icon', models.CharField(blank=True, help_text='Font Awesome icon class', max_length=50)),
                ('color', models.CharField(default='primary', help_text='Button color class (primary, secondary, accent, etc.)', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DownloadLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('order', models.IntegerField(default=0)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_links', to='blog.post')),
                ('host_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.hosttype')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
