# Generated by Django 5.2 on 2025-04-28 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_hosttype_downloadlink'),
        ('shortlink', '0002_alter_shortlink_short_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadlink',
            name='short_link',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='download_link', to='shortlink.shortlink'),
        ),
    ]
