# Generated by Django 5.2 on 2025-04-28 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_downloadlink_short_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Actresses',
            },
        ),
        migrations.AddField(
            model_name='post',
            name='actresses',
            field=models.ManyToManyField(blank=True, related_name='posts', to='blog.actress'),
        ),
    ]
