# Generated by Django 5.2 on 2025-04-28 09:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_actress_post_actresses'),
        ('shortlink', '0002_alter_shortlink_short_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Manga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('pdf_file', models.FileField(upload_to='manga_pdfs/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='manga_thumbnails/')),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manga', to=settings.AUTH_USER_MODEL)),
                ('categories', models.ManyToManyField(related_name='manga', to='blog.category')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MangaDownloadLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('order', models.IntegerField(default=0)),
                ('host_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.hosttype')),
                ('manga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_links', to='blog.manga')),
                ('short_link', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manga_download_link', to='shortlink.shortlink')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
