# Generated by Django 5.2 on 2025-04-28 10:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_manga_mangadownloadlink'),
        ('shortlink', '0002_alter_shortlink_short_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MangaAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Manga Authors',
            },
        ),
        migrations.CreateModel(
            name='MangaCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Manga Categories',
            },
        ),
        migrations.CreateModel(
            name='MangaTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Manga Tags',
            },
        ),
        migrations.RemoveField(
            model_name='manga',
            name='author',
        ),
        migrations.RemoveField(
            model_name='manga',
            name='categories',
        ),
        migrations.AddField(
            model_name='manga',
            name='download_shortlink',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manga_download', to='shortlink.shortlink'),
        ),
        migrations.AddField(
            model_name='manga',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='manga',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mangas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='manga',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='manga',
            name='pdf_file',
            field=models.FileField(upload_to='manga/pdfs/'),
        ),
        migrations.AlterField(
            model_name='manga',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='manga/thumbnails/'),
        ),
        migrations.AddField(
            model_name='manga',
            name='manga_authors',
            field=models.ManyToManyField(related_name='mangas', to='blog.mangaauthor'),
        ),
        migrations.AddField(
            model_name='manga',
            name='manga_categories',
            field=models.ManyToManyField(related_name='mangas', to='blog.mangacategory'),
        ),
        migrations.AddField(
            model_name='manga',
            name='manga_tags',
            field=models.ManyToManyField(related_name='mangas', to='blog.mangatag'),
        ),
        migrations.DeleteModel(
            name='MangaDownloadLink',
        ),
    ]
