# Generated by Django 5.1.7 on 2025-04-29 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_bookmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_member_post',
            field=models.BooleanField(default=False, help_text='Check if this is a member-created post rather than an official post'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='points',
            field=models.PositiveIntegerField(default=0, help_text='Points earned from user interactions with posts'),
        ),
    ]
