# Generated by Django 5.2 on 2025-04-30 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_post_is_member_post_userprofile_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manga',
            name='manga_categories',
        ),
    ]
